/**
 * Accessors over the build-time documentation index.
 *
 * The index itself is generated by `plugins/docs-plugin.ts` and injected as the
 * virtual module `virtual:docs-index`. Nothing here parses content at runtime.
 */
import { contentLoaders, docIndex } from 'virtual:docs-index'
import type { DocFolder, DocIndex, DocNode, DocPage } from './docs.types'
import { isFolder } from './docs.types'
import { normalizePath } from './routing'

export const docs: DocIndex = docIndex

export function getPage(pathname: string): DocPage | undefined {
  return docs.byPath[normalizePath(pathname)]
}

export function getFolder(pathname: string): DocFolder | undefined {
  return docs.foldersByPath[normalizePath(pathname)]
}

export const topLevelFolders = (): DocFolder[] => docs.tree

/** In-memory cache of article bodies already fetched this session. */
const contentCache = new Map<string, string>()

export function getCachedContent(path: string): string | undefined {
  return contentCache.get(normalizePath(path))
}

/**
 * Fetches a page's compiled HTML. The first call for a path loads its chunk;
 * subsequent calls resolve from cache, so returning to a page is instant.
 */
export async function loadContent(path: string): Promise<string> {
  const key = normalizePath(path)
  const cached = contentCache.get(key)
  if (cached !== undefined) return cached

  const loader = contentLoaders[key]
  if (!loader) return ''

  const mod = await loader()
  contentCache.set(key, mod.html)
  return mod.html
}

/** Counts every page beneath a node — used for folder summaries. */
export function countPages(node: DocNode): number {
  if (!isFolder(node)) return 1
  return node.children.reduce((total, child) => total + countPages(child), 0)
}

/**
 * Returns the set of folder paths that must be expanded for `pathname` to be
 * visible in the sidebar, i.e. every ancestor of the active page.
 */
export function ancestorFolderPaths(pathname: string): string[] {
  const current = normalizePath(pathname)
  const out: string[] = []

  const walk = (nodes: DocNode[], trail: string[]): boolean => {
    for (const node of nodes) {
      if (isFolder(node)) {
        const nextTrail = [...trail, node.path]
        if (current === node.path) {
          out.push(...nextTrail)
          return true
        }
        if (walk(node.children, nextTrail)) return true
      } else if (node.path === current) {
        out.push(...trail)
        return true
      }
    }
    return false
  }

  walk(docs.tree, [])
  return out
}

/** Every folder path in the tree, for the "Expand all" control. */
export function allFolderPaths(): string[] {
  const out: string[] = []
  const walk = (nodes: DocNode[]): void => {
    for (const node of nodes) {
      if (isFolder(node)) {
        out.push(node.path)
        walk(node.children)
      }
    }
  }
  walk(docs.tree)
  return out
}
